### ISSUE TITLE
Make normalized versioning

### ISSUE THREAD

**Issue by Romick2005** [Countly/countly-sdk-react-native-bridge#199]
Can you please do no use leading zeros in version?
Because all users would get this as output of `npm outdated` command:
![image](https://user-images.githubusercontent.com/17779660/236798144-2b3fca8c-7058-47e4-bd51-e211ecf5e368.png)

**Comment by peterbrown0** [comment]
Hello,
Thank you for bringing this to our attention.
We already were planning to drop the leading zero for the second version number.
This change would happen with the next release of this SDK.
