### ISSUE TITLE
[iOS] push notifications are not received on 23.x.x version

### ISSUE THREAD

**Issue by zakharchenkoAndrii** [Countly/countly-sdk-react-native-bridge#204]
`Countly.pushTokenType` method has been deprecated
in favor of `CountlyConfig.pushTokenType`

The method from CountlyConfig is not working on **iOS** while the deprecated one from Countly.js **works fine**.
I am receiving the following error: 

<img width="1121" alt="image" src="https://github.com/Countly/countly-sdk-react-native-bridge/assets/23197387/9665124f-782c-4cad-98b0-2c901c620d04">

From our side, we are setting this method right and values are set correctly.
{...other fields
"channelDescription": "", "channelName": "Our Channel name", "consents": ["users", "remote-config", "apm", "events", "location", "sessions", "views", "push"], "deviceID": "my device ID", "enableApm": true, "tokenType": "1"}

Notes:
We call `Countly.askForNotificationPermission()` _after_  initialization with config so our steps are correct as previous implementation worked fine (on 22.6.5) + Android works fine even with setting `pushTokenType` via config

**Comment by ArtursKadikis** [comment]
Hello, thank you for bringing this up.

This bug has been fixed in the latest (23.2.3) release.

**Comment by zakharchenkoAndrii** [comment]
Great! Thanks
