### ISSUE TITLE
Unclear param type for `configureIntentRedirectionCheck`

### ISSUE THREAD

**Issue by zakharchenkoAndrii** [Countly/countly-sdk-react-native-bridge#206]
your doc comment says:
```
   /**
    * Method to configure intent redirection check
    *
    * @param {String} allowedIntentClassNames allowedIntentClassNames
    * @param {String} allowedIntentPackageNames allowedIntentPackageNames
    */
    configureIntentRedirectionCheck(allowedIntentClassNames, allowedIntentPackageNames) {
        this.allowedIntentClassNames = allowedIntentClassNames;
        this.allowedIntentPackageNames = allowedIntentPackageNames;
        return this;
    }
```
previously `allowedIntentClassNames, allowedIntentPackageNames` were `String[]` type. Now you say that it is just `String`
however naming is _still_ plural allowedIntentClassName**S**. 

I _could_ create PR and change either type to `array of Strings` or change naming to be singular but I don't know what was your intention during this refactoring.

Also, what happened with `useAdditionalIntentRedirectionChecks` param? is it gone and will be by default true always?

**Comment by ArtursKadikis** [comment]
Hello, thank you for bringing this up.

That comment was wrong and it should be an array of strings.

Currently that param defaults to "true". We will adding a call to configure this value with the config class.

**Comment by zakharchenkoAndrii** [comment]
Okay, thank you 🙂

**Comment by turtledreams** [comment]
Hello, added `disableAdditionalIntentRedirectionChecks` with version 24.4.0 to disable additional intent redirection checks: https://support.count.ly/hc/en-us/articles/360037813231-React-Native-Bridge#h_01HAVQNJQSDMY43FAAN5D1GQ74
