### ISSUE TITLE
ReferenceError: Property 'eventEmitter' doesn't exist (new Countly.feedback interface)

### ISSUE THREAD

**Issue by km4r** [Countly/countly-sdk-react-native-bridge#246]
Hello,

I wanted to remove deprecated code after SDK upgrade (23.8.0) in my app, but looks like the new Feedback interface is causing some issues.

I switched `Countly.presentFeedbackWidgetObject` to `Countly.feedback.presentFeedbackWidget` and now I get an error:

```
ReferenceError: Property 'eventEmitter' doesn't exist
```

Looks like `widgetShownCallback` and `widgetClosedCallback` are not handled properly.

Checked on Android and iOS.
react: 18.2.0
react-native: 0.71.7
countly-sdk-react-native-bridge: 23.8.0
Countly server: enterprise 23.06.6

**Comment by peterBrxwn** [comment]
Thank you for bringing this to our notice. We have seen the bug, and we are working on it. We will release the fix later today.

**Comment by peterBrxwn** [comment]
Hello @km4r, this bug has been fixed, and a new version (23.8.1) has been released.

**Comment by km4r** [comment]
I confirm it's fixed, thank you!

But one little thing - now it looks like `widgetShownCallback` and `widgetClosedCallback` params are mandatory. For example if the "closed" callback is missing I get a warning:
```
Sending `widgetClosedCallback` with no listeners registered.
```

I think in this case it shouldn't trigger any listeners or warnings.

**Comment by peterBrxwn** [comment]
Hello @km4r, I could not reproduce this.

I called `Countly.feedback.presentFeedbackWidget` without `widgetClosedCallback` callback and got no warnings on both iOS and Android. Can you send me a code snippet (and platform) to try?

react: 18.2.0
react-native: 0.71.0
countly-sdk-react-native-bridge: 23.8.1
