### ISSUE TITLE
Not able to send any info to server using sdk

### ISSUE THREAD

**Issue by ningliu** [Countly/countly-sdk-react-native-bridge#3]
I tried the example provided, but not able to send any info to the Countly server.  Here are my steps:
1. I followed the instruction here:
https://github.com/Countly/countly-sdk-react-native-bridge/tree/master/example

2. I replaced the server url and app_key with the correct values.

3. I am running ios

I am pretty sure my Countly server is set up correctly, because I am able to use the REST API to send the info.  I use Postman.
Could you please take a look?
Please let me know what other info I need to provide.

**Comment by pembeci** [comment]
After starting the app fresh, please press these buttons: "Init", then "Start", then "Basic Events". Are you able to see user's session and the event on server side?

**Comment by ningliu** [comment]
I checked again, still doesn't work.
I used mongo shell to check the db directly.  It has all the data I sent through rest api, but not through the example app.
The data I am checking is "events" and "event{ID}".
"db.events.find({})" should list all the events ever recorded, right?

From the Countly dashboard, there is no session data.
I did not try session through REST API.
I haven't looked into session data in DB yet.

**Comment by pembeci** [comment]
You are using App Key not App ID, right? App Key is the longer one and used with SDK. If that one is correct may be @nicolsondsouza or @trinisofttechnologies can help with IOS. I know Android part better. Is it an option for you to test your app on Android? You may try calling `Countly.enableLogging();` just after you call `Countly.Init`and check the logs.

**Comment by ningliu** [comment]
I am using App Key.  Android works for me. 
How to check the logs?

**Comment by trinisofttechnologies** [comment]
Hi @ningliu 

Can you check follow. 
1. Can you let me know whether are you test App.(Device or Simulator)
2. Please make sure Internet is Connected.
3. Can you make sure "server url" and "app_key" is correct? 

I just tested SDK and made sure it working fine so there must be issue with the setup. If you still have issue we can get on telco call and can help you setup.

**Comment by ningliu** [comment]
After I restart everything including my mac, everything starts working.  Thank you for your patience!
