### ISSUE TITLE
Document breaking changes in README

### ISSUE THREAD

**Issue by HolySamosa** [Countly/countly-sdk-react-native-bridge#31]
Please add a section to the main README that documents breaking changes.  (We ran into an issue `setViewTracking()` being removed, however this was not documented.)

**Comment by ArtursKadikis** [comment]
That was removed because it's not needed and didn't add any value. You can just update your SDK version and remove it.

**Comment by HolySamosa** [comment]
@ArtursKadikis - I respectfully disagree about documentation of breaking changes not adding value.  Had breaking changes been documented, I could have avoiding wasting several valuable hours last week.  

After upgrading `countly-sdk-react-native-bridge`, our app began crashing in the bridge native code-- which crashes the RN debug build, meaning no access to RN logs.  In firing up Xcode, we then begin seeing messages about the `setViewTracking` selector being undefined, sending us down a dead end.  Ultimately, the native crash was caused by `init()` no longer accepting an empty parameter, as discussed in #10.  However, the suggested solution did not work for us-- we instead had to resort to setting `TemporaryDeviceID` as the 3rd param to `init()`. 

Which brings us back to `setViewTracking`, which was not crashing on the JS side.  Since this removal wasn't documented anywhere I had to resort to code diffs and your projects git history to ultimately figure out that automatic view tracking had been removed (which we were not using).

So, documenting your breaking changes saves your developers their very valuable time. Please consider reopening this issue.

Thanks.

**Comment by ArtursKadikis** [comment]
Sorry to hear that you had to spend so much time on this, but I never said that documentation of breaking is not adding value. I meant that the discussed call did not add any value.
