### ISSUE TITLE
Access documentation for older versions of countly-sdk-react-native-bridge

### ISSUE THREAD

**Issue by HolySamosa** [Countly/countly-sdk-react-native-bridge#32]
Please keep documentation accessible for older versions of `countly-sdk-react-native-bridge`.  The docs on https://support.count.ly/ only pertain to the latest documented release.

**Comment by ArtursKadikis** [comment]
When possible, we try to do that. What entry/explanation is missing from the current doc?

**Comment by HolySamosa** [comment]
@ArtursKadikis `setViewTracking()` and automatic view tracking, specifically.  I was trying to use documentation to make sense of the breaking changes we were seeing (#31).
