### ISSUE TITLE
Malformed GET requests sent to the API?

### ISSUE THREAD

**Issue by HolySamosa** [Countly/countly-sdk-react-native-bridge#33]
After upgrading to 20.4.9, our Countly server no longer receives data from our app.  Looking at the iOS console, if appears that malformed GET requests are being generated, resulting in a server error of "App does not exist":

```
13:27:56.481122-0500	My CEP Beta		default	My CEP Beta	[Countly] Request <0x60000b399120> started:
[GET] https://countly.ipat.gatech.edu/i?app_key=APP_KEY_REDACTED202320My<decode: mismatch for [%20C] got [OBJECT private sz:520]>EP20Beta20key&device_id=0033F00000RSFI2QAP&timestamp=1604094249254&hour=17&dow=5&tz=-240&sdk_version=20.04.9&sdk_name=js-rnb-ios&begin_session=1&metrics=7B22_device22<decode: missing data><decode: missing data>86_6422<decode: missing data>22_os_version22<decode: missing data>2214.122<decode: missing data>22_locale22<decode: missing data><decode: missing data>n_US22<decode: missing data>22_density22<decode: missing data>22<decode: missing data>22<decode: missing data>22_app_version22<decode: missing data>220.9.022<decode: missing data>22_resolution22<decode: missing data><decode: missing data>216022<decode: missing data>22_os22<decode: missing data><decode: missing data>OS22<decode: missing data>
13:27:56.551418-0500	My CEP Beta		default	My CEP Beta	[Countly] Request <0x60000b399120> failed!
Server reply: {"result":"App does not exist"}
```

Also: Since we need to get a new version of our app out ASAP, what version of the bridge would you consider stable and recommend? Thanks!

**Comment by ijunaid** [comment]
Hello,
It looks like that app_key is not correct.
Here are the steps you need to do:
- Recheck that Countly SDK is initialized with the correct App key.
- Uninstall and reinstall the app.

**Comment by HolySamosa** [comment]
Thanks, @ijunaid.  The `app_key` value provided to the SDK is correct-- (I've redacted it in the above logs).  You'll see from the logging of the GET request, that the `app_key` parameter is being corrupted (e.g. it shouldn't include `<decode: mismatch for [%20C] got [OBJECT private sz:520]>`).

In the meantime, is there a version of the SDK that you would recommend as stable?  We upgraded to 20.4.9 from commit 891ac24da07b8c2938db861fdfbc3b895669a7cc (July 5, prior to 20.4.5), which we were using to work around an issue we had with 20.4.4.  We were driven to the latest upgrade after seeing issues of the SDK intermittently failing to initialize.

Thanks for the assistance!

**Comment by ijunaid** [comment]
20.4.9 is the latest stable release, it is the recommended version to use.
Have you tried to uninstall and reinstall the app?
Also, share your initialization code of Countly SDK.

**Comment by HolySamosa** [comment]
@ijunaid Sorry-- this one was on our end.  A comment from the config .env file with the API key was being included as part of the API key value.  

But it does seem like there is an issue with the Countly logging on iOS-- the `<decode: mismatch ` values logged in the GET request suggested that the GET request itself was malformed.
