### ISSUE TITLE
podspec version needs to be updated when native code changes

### ISSUE THREAD

**Issue by HolySamosa** [Countly/countly-sdk-react-native-bridge#34]
The version given in the `CountlyReactNative.podspec` file hasn't been updated as there have been changes to the iOS native module.  Thus, when we try to build different branches of our app using different versions of the Countly SDK, the `pod install` step does not necessarily install the correct version of `CountlyReactNative`.   E.g. 20.4.4 and 20.4.9 both version `CountlyReactNative` as 20.4.  Install 20.4.4 and then 20.4.9-- the latter will then be using the wrong `CountlyReactNative` module.

**Comment by ArtursKadikis** [comment]
Hello, this problem has been solved.
