### ISSUE TITLE
Can you add a way to turn off push notification app delegate methods swizzling, please?

### ISSUE THREAD

**Issue by backmeupplz** [Countly/countly-sdk-react-native-bridge#43]
We can't quite use Firebase for push notifications on iOS because Countly swizzles push notification methods after the Firebase setup. We'd like to turn off push notifications for the Countly SDK from the react native side.

It is turned on in `CountlyReactNative.m:62` and there is no way to avoid swizzling. Can we make it configurable? Or at least maybe there is a way to avoid swizzling?

**Comment by backmeupplz** [comment]
Or maybe at least support this? https://github.com/Countly/countly-sdk-ios/commit/2b89dc13524d695f05d4e8bb2461521a8f89b377

**Comment by ArtursKadikis** [comment]
This issue should have already been fixed by this PR #46
