### ISSUE TITLE
Breaks other push notifications libraries

### ISSUE THREAD

**Issue by andreialecu** [Countly/countly-sdk-react-native-bridge#55]
I've been troubleshooting a problem with `react-native-notifications` behaving erratically and tracked it down to a conflict with `countly-sdk-react-native-bridge`

The problem seems to be related to:
https://github.com/Countly/countly-sdk-react-native-bridge/blob/a0ebf0773e4638d87ed69aee5e95f61e8d74e903/ios/src/CountlyReactNative.m#L32

https://github.com/Countly/countly-sdk-react-native-bridge/blob/a0ebf0773e4638d87ed69aee5e95f61e8d74e903/ios/src/CountlyReactNative.m#L64-L66

The above lines seem to be ran on startup, without any way to prevent the hijack from ocurring.

I originally tried using `COUNTLY_EXCLUDE_PUSHNOTIFICATIONS` (as per https://github.com/Countly/countly-sdk-ios/commit/2b89dc13524d695f05d4e8bb2461521a8f89b377) but enabling it resulted in compilation errors inside `CountlyReactNative.m` because the implementation was missing.

Even providing `COUNTLY_EXCLUDE_PUSHNOTIFICATIONS` is a bit unintuitive:
```
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "CountlyReactNative"
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'COUNTLY_EXCLUDE_PUSHNOTIFICATIONS=1']
        end
      end
    end

    react_native_post_install(installer)
  end
```

Original report in:
https://github.com/wix/react-native-notifications/issues/561#issuecomment-824746532

**Comment by andreialecu** [comment]
It appears that running:

```ts
    Countly.disablePushNotifications();
    Countly.init(serverURL, appKey, deviceId);
```
Does fix the breakage.

However, I'd like to be able to use `COUNTLY_EXCLUDE_PUSHNOTIFICATIONS` to disable this entirely.

I think the documentation should make it obvious that this will break other existing push implementations. 

It would even be better to make `enablePushNotifications()` an opt-in, instead of it applying by default. I think this is critical, otherwise adding this library is going to break existing apps in unexpected ways.

**Comment by ijunaid** [comment]
Hi @andreialecu,

Like you already noticed, push integration is added is enabled by default. We are considering changing that in the future but there are of course complications surrounding that.
We are planning to add 'COUNTLY_EXCLUDE_PUSHNOTIFICATIONS' in our next release.

**Comment by ArtursKadikis** [comment]
The release to fix this has been published.
