### ISSUE TITLE
setupPush is not a function

### ISSUE THREAD

**Issue by izaanjahangir** [Countly/countly-sdk-react-native-bridge#6]
I am setting push notification using countly on react native and on android i am facing this error

![Screenshot_1574775182](https://user-images.githubusercontent.com/38363867/69637819-3dad2280-107b-11ea-9334-9dbd1860d482.png)

I followed the guide provided in the guide [here](https://github.com/Countly/countly-sdk-react-native-bridge/tree/master/example/android_push)

I further goes  to the library code and i can see that there is no setupPush function is available in the library

thanks

**Comment by pembeci** [comment]
Hello. Did you do this part from that guide?

> Critical change in MainApplication.java to use new native module CountlyReactNativePush is this part:

```
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:      
      packages.add(new CountlyReactNativePushPackage());
      return packages;
    }
```

`setupPush` is now in an extra module defined in [`CountlyReactNativePush.java`](https://github.com/Countly/countly-sdk-react-native-bridge/blob/master/example/android_push/CountlyReactNativePush.java) but you need to update your `MainApplication.java` as above in order  to link to that module.

**Comment by izaanjahangir** [comment]
yes

![countly](https://user-images.githubusercontent.com/38363867/69753268-00c55680-1175-11ea-8630-f597c062769b.PNG)

**Comment by pembeci** [comment]
What you pointed is the main native package. This is extra: new CountlyReactNative**Push**Package(). As you can see from example App.js from that guide you need to use it like this:

```
const CountlyPush = NativeModules.CountlyReactNativePush;

var options = { channelName: "Demo App Notifications", channelDescription: "<![CDATA[Messages from Demo App]]>"}
CountlyPush.setupPush(Countly.messagingMode.DEVELOPMENT, options);
// optional, if you need to console log 
DeviceEventEmitter.addListener('push_notification', payload => {
     console.log("Notification received", payload);
});
```
From your error message I can see that you are not calling setupPush from `NativeModules.CountlyReactNativePush` and this extra push specific native package is not in your package list.

**Comment by izaanjahangir** [comment]
ok let me try this

**Comment by izaanjahangir** [comment]
yes, it worked thanks alot :-D

**Comment by pembeci** [comment]
Glad it worked. I see that our github guide and official docs diverged after we separated push functionality into its own native module. So may be that's what confused you. I'll update the docs.

**Comment by izaanjahangir** [comment]
thanks for your quick support
