### ISSUE TITLE
iOS - String sent via setEventSendThreshold not converted to Unsigned Int

### ISSUE THREAD

**Issue by jeffsteinmetz** [Countly/countly-sdk-react-native-bridge#7]
at

https://github.com/Countly/countly-sdk-react-native-bridge/blob/master/ios/src/CountlyReactNative.m#L586

```
RCT_EXPORT_METHOD(setEventSendThreshold:(NSArray*)arguments)
{
  NSString* size = [arguments objectAtIndex:0];
  if (config == nil){
    config = CountlyConfig.new;
  }
  config.eventSendThreshold = size;
}
```
` config.eventSendThreshold` is expecting a NSUInteger, not a string

calling `Countly.setEventSendThreshold(1);` from react-native appears to make no difference

(not sure if this is also a potential area to investigate in Java / Android)

**Comment by pembeci** [comment]
Thanks for reporting this Jeff. We fixed it and will go through other arguments that may need type casting.
