### ISSUE TITLE
Build error: Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported`

### ISSUE THREAD

**Issue by andreialecu** [Countly/countly-sdk-react-native-bridge#70]
Getting this error after making the necessary adjustments to a project to use RN 0.67:

```
node_modules/countly-sdk-react-native-bridge/android/src/main/AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.
```

**Comment by andreialecu** [comment]
This might serve as inspiration:
https://github.com/wix/react-native-notifications/blob/master/lib/android/app/src/main/AndroidManifest.xml#L13-L26

This library had the same issue but fixed it. I'm not sure if true or false should be applied for countly.

**Comment by octobus55** [comment]
For anyone interested I made this fork for this problem https://github.com/octobus55/countly-sdk-react-native-bridge

**Comment by ArtursKadikis** [comment]
Hello, this should already be handeld by the past few releases.
